[book]
authors = ["Seasawher"]
language = "ja"
multilingual = false
src = "src"
title = "Functional Programming in Lean 日本語訳"

[build]

[preprocessor.buildexamples]
command = "python -X utf8 scripts/build-examples.py"
before = ["leanexample", "commands"]

[preprocessor.leanexample]
command = "python -X utf8 scripts/example.py"

[preprocessor.commands]
command = "python -X utf8 scripts/projects.py"

[preprocessor.leanversion]
command = "python -X utf8 scripts/lean-version.py"

[output.html]
additional-css = ["custom.css", "pygments.css"]
mathjax-support = true
git-repository-url = "https://github.com/s-taiga/fpil-ja"

#[output.pandoc]
#command = "python -X utf8 ../../scripts/one-markdown.py"

[output.fancywordcount]
command = "python -X utf8 ../../scripts/wc.py"
